[2025-08-05T23:15:19.399+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.Inicio manual__2025-08-05T23:15:05.658893+00:00 [queued]>
[2025-08-05T23:15:19.438+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.Inicio manual__2025-08-05T23:15:05.658893+00:00 [queued]>
[2025-08-05T23:15:19.440+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T23:15:19.488+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Inicio> on 2025-08-05 23:15:05.658893+00:00
[2025-08-05T23:15:19.515+0000] {standard_task_runner.py:60} INFO - Started process 3082 to run task
[2025-08-05T23:15:19.526+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'Inicio', 'manual__2025-08-05T23:15:05.658893+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmp_v68insg']
[2025-08-05T23:15:19.536+0000] {standard_task_runner.py:88} INFO - Job 207: Subtask Inicio
[2025-08-05T23:15:19.830+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.Inicio manual__2025-08-05T23:15:05.658893+00:00 [running]> on host 019b67754667
[2025-08-05T23:15:20.286+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='Inicio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T23:15:05.658893+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T23:15:05.658893+00:00'
[2025-08-05T23:15:20.339+0000] {logging_mixin.py:188} INFO - -------------------------TABLES------------------
[2025-08-05T23:15:20.340+0000] {logging_mixin.py:188} INFO - --dimcustomersegment---
[2025-08-05T23:15:20.341+0000] {logging_mixin.py:188} INFO - --dimdate---
[2025-08-05T23:15:20.342+0000] {logging_mixin.py:188} INFO - --dimproduct---
[2025-08-05T23:15:20.343+0000] {logging_mixin.py:188} INFO - --factsales---
[2025-08-05T23:15:20.345+0000] {logging_mixin.py:188} INFO - TABLAS PRECARGADAS
[2025-08-05T23:15:20.348+0000] {python.py:201} INFO - Done. Returned value was: cargaincremental
[2025-08-05T23:15:20.349+0000] {branch.py:35} INFO - Branch into cargaincremental
[2025-08-05T23:15:20.350+0000] {skipmixin.py:178} INFO - Following branch cargaincremental
[2025-08-05T23:15:20.373+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaincremental'}.
[2025-08-05T23:15:20.389+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=Inicio, execution_date=20250805T231505, start_date=20250805T231519, end_date=20250805T231520
[2025-08-05T23:15:20.428+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 207 for task Inicio ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaincremental'}.; 3082)
[2025-08-05T23:15:20.455+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T23:15:20.527+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
