[2025-08-04T23:04:03.074+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.ver_tablas_postgres scheduled__2025-08-04T23:02:00+00:00 [queued]>
[2025-08-04T23:04:03.113+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.ver_tablas_postgres scheduled__2025-08-04T23:02:00+00:00 [queued]>
[2025-08-04T23:04:03.114+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T23:04:03.271+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): ver_tablas_postgres> on 2025-08-04 23:02:00+00:00
[2025-08-04T23:04:03.293+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2025-08-04T23:04:03.379+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'ver_tablas_postgres', 'scheduled__2025-08-04T23:02:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmp75bm_iwk']
[2025-08-04T23:04:03.384+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask ver_tablas_postgres
[2025-08-04T23:04:03.719+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.ver_tablas_postgres scheduled__2025-08-04T23:02:00+00:00 [running]> on host 521155ff77c9
[2025-08-04T23:04:03.999+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='ver_tablas_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T23:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-04T23:02:00+00:00'
[2025-08-04T23:04:04.004+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-04T23:04:04.007+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    psql -h $POSTGRES_HOST -U $POSTGRES_USUARIO -d $POSTGRES_DB_REPLICA -c "\\dt"\n    ']
[2025-08-04T23:04:04.059+0000] {subprocess.py:86} INFO - Output:
[2025-08-04T23:04:04.492+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "-U" to address: Name or service not known
[2025-08-04T23:04:04.495+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-04T23:04:04.552+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-04T23:04:04.573+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=ver_tablas_postgres, execution_date=20250804T230200, start_date=20250804T230403, end_date=20250804T230404
[2025-08-04T23:04:04.704+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task ver_tablas_postgres (Bash command failed. The command returned a non-zero exit code 2.; 186)
[2025-08-04T23:04:04.900+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T23:04:05.061+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
