[2025-08-05T23:23:19.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.Updatedimcustomersegment manual__2025-08-05T23:18:00.150544+00:00 [queued]>
[2025-08-05T23:23:19.138+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.Updatedimcustomersegment manual__2025-08-05T23:18:00.150544+00:00 [queued]>
[2025-08-05T23:23:19.139+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-05T23:23:19.174+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Updatedimcustomersegment> on 2025-08-05 23:18:00.150544+00:00
[2025-08-05T23:23:19.189+0000] {standard_task_runner.py:60} INFO - Started process 3256 to run task
[2025-08-05T23:23:19.196+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'Updatedimcustomersegment', 'manual__2025-08-05T23:18:00.150544+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpedask3zf']
[2025-08-05T23:23:19.203+0000] {standard_task_runner.py:88} INFO - Job 226: Subtask Updatedimcustomersegment
[2025-08-05T23:23:19.308+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.Updatedimcustomersegment manual__2025-08-05T23:18:00.150544+00:00 [running]> on host 019b67754667
[2025-08-05T23:23:19.493+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='Updatedimcustomersegment' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T23:18:00.150544+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T23:18:00.150544+00:00'
[2025-08-05T23:23:20.362+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/stg_dimcustomersegment?select=%2A "HTTP/2 200 OK"
[2025-08-05T23:23:20.400+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 144, in call
    update_inactive(table,id,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 46, in update_inactive
    comparison = df.merge(df_supabase,on=[id],how='outer',indicator=True,suffixes=('_PG', '_SP'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'segmentid'
[2025-08-05T23:23:20.473+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Ejercicio1, task_id=Updatedimcustomersegment, execution_date=20250805T231800, start_date=20250805T232319, end_date=20250805T232320
[2025-08-05T23:23:20.515+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 226 for task Updatedimcustomersegment ('segmentid'; 3256)
[2025-08-05T23:23:20.579+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T23:23:20.649+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
